on:
  push:
    branches:
    - master
  pull_request:
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, 1.20.x]
        platform: [ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get install libicu-dev libleveldb-dev librocksdb-dev
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go version
        CGO_LDFLAGS="-lrocksdb" go test -race ./...
